# المنفذ الرئيسي للنظام بأكمله
server:
  port: 8080

# اسم التطبيق كما سيظهر في يوريكا
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # تفعيل البحث عن الخدمات عبر يوريكا
      discovery:
        locator:
          enabled: true
      # تعريف قواعد التوجيه (Routing Rules)
      routes:
        # توجيه الطلبات الخاصة بخدمة المستخدمين
        - id: user-service-route
          uri: lb://USER-SERVICE # lb تعني Load Balancer، سيبحث في يوريكا عن خدمة اسمها USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**

        # توجيه الطلبات الخاصة بخدمة الدورات
        - id: course-service-route
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/v1/courses/**

        # توجيه الطلبات الخاصة بخدمة التسجيل
        - id: enrollment-service-route
          uri: lb://ENROLLMENT-SERVICE
          predicates:
            - Path=/api/v1/enrollments/**, /api/v1/users/{userId}/enrollments/**

        # توجيه الطلبات الخاصة بخدمة التقييمات
        - id: assessment-service-route
          uri: lb://ASSESSMENT-SERVICE
          predicates:
            - Path=/api/v1/assessments/**

# تحديد مكان خادم يوريكا
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/